#python项目的ruff相关配置. 默认放在项目根目录. 如果项目目录找不,自动去以下文件找linux: ~/.config/ruff/pyproject.toml, mac: ~/Library/Application Support/ruff/pyproject.toml 
[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "C9", # pycodestyle errors
    "Q",  # flake8-quotes
    "RET", # flake8-return
    "PTH", # flake8-pathlib
    "FIX", # flake8-fixme
]
line-length = 120
unsafe-fixes = true # fix all errors that can be fixed automatically

[tool.ruff.lint]
fixable=["ALL"]
unfixable = ["F401"]
ignore = ["TD003", "RET505", "E501"]


[tool.ruff.per-file-ignores]
# ignore unused imports in __init__.py files

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 15 

[tool.ruff.isort]
known-third-party = ["django", "celery"]

known-first-party = ["cost_control", "cloud_driver", "data_warehouse", "common", "cmdb_api", "third_party_api", "enhanced_cmdb"]
